/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VendorSupportRouteImport } from './routes/vendor.support'
import { Route as VendorRevenueRouteImport } from './routes/vendor.revenue'
import { Route as VendorProfileRouteImport } from './routes/vendor.profile'
import { Route as VendorProductsRouteImport } from './routes/vendor.products'
import { Route as VendorOrdersRouteImport } from './routes/vendor.orders'
import { Route as VendorNotificationsRouteImport } from './routes/vendor.notifications'
import { Route as VendorMessagesRouteImport } from './routes/vendor.messages'
import { Route as VendorInventoryRouteImport } from './routes/vendor.inventory'
import { Route as VendorDashboardRouteImport } from './routes/vendor.dashboard'
import { Route as DriverTripsRouteImport } from './routes/driver.trips'
import { Route as DriverSupportRouteImport } from './routes/driver.support'
import { Route as DriverProfileRouteImport } from './routes/driver.profile'
import { Route as DriverNotificationsRouteImport } from './routes/driver.notifications'
import { Route as DriverIssuesRouteImport } from './routes/driver.issues'
import { Route as DriverHomeRouteImport } from './routes/driver.home'
import { Route as DriverEarningsRouteImport } from './routes/driver.earnings'
import { Route as CustomerVouchersRouteImport } from './routes/customer.vouchers'
import { Route as CustomerSupportRouteImport } from './routes/customer.support'
import { Route as CustomerSearchRouteImport } from './routes/customer.search'
import { Route as CustomerProfileRouteImport } from './routes/customer.profile'
import { Route as CustomerNotificationsRouteImport } from './routes/customer.notifications'
import { Route as CustomerHomeRouteImport } from './routes/customer.home'
import { Route as CustomerFavoritesRouteImport } from './routes/customer.favorites'
import { Route as CustomerCheckoutRouteImport } from './routes/customer.checkout'
import { Route as CustomerCartRouteImport } from './routes/customer.cart'
import { Route as CustomerAddressesRouteImport } from './routes/customer.addresses'
import { Route as AdminVouchersRouteImport } from './routes/admin.vouchers'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminTicketsRouteImport } from './routes/admin.tickets'
import { Route as AdminStallsRouteImport } from './routes/admin.stalls'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminReportsRouteImport } from './routes/admin.reports'
import { Route as AdminProductsRouteImport } from './routes/admin.products'
import { Route as AdminOrdersRouteImport } from './routes/admin.orders'
import { Route as AdminNotificationsRouteImport } from './routes/admin.notifications'
import { Route as AdminMarketsRouteImport } from './routes/admin.markets'
import { Route as AdminDriversRouteImport } from './routes/admin.drivers'
import { Route as AdminDispatchRouteImport } from './routes/admin.dispatch'
import { Route as AdminDashboardRouteImport } from './routes/admin.dashboard'
import { Route as CustomerOrdersIndexRouteImport } from './routes/customer.orders.index'
import { Route as VendorProductsNewRouteImport } from './routes/vendor.products.new'
import { Route as VendorOrdersIdRouteImport } from './routes/vendor.orders.$id'
import { Route as DriverTripsIdRouteImport } from './routes/driver.trips.$id'
import { Route as CustomerStallsIdRouteImport } from './routes/customer.stalls.$id'
import { Route as CustomerProfileEditRouteImport } from './routes/customer.profile.edit'
import { Route as CustomerProductsIdRouteImport } from './routes/customer.products.$id'
import { Route as CustomerMarketsIdRouteImport } from './routes/customer.markets.$id'
import { Route as CustomerCategorySlugRouteImport } from './routes/customer.category.$slug'
import { Route as CustomerOrdersIdTrackingRouteImport } from './routes/customer.orders.$id.tracking'
import { Route as CustomerOrdersIdRateRouteImport } from './routes/customer.orders.$id.rate'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VendorSupportRoute = VendorSupportRouteImport.update({
  id: '/vendor/support',
  path: '/vendor/support',
  getParentRoute: () => rootRouteImport,
} as any)
const VendorRevenueRoute = VendorRevenueRouteImport.update({
  id: '/vendor/revenue',
  path: '/vendor/revenue',
  getParentRoute: () => rootRouteImport,
} as any)
const VendorProfileRoute = VendorProfileRouteImport.update({
  id: '/vendor/profile',
  path: '/vendor/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const VendorProductsRoute = VendorProductsRouteImport.update({
  id: '/vendor/products',
  path: '/vendor/products',
  getParentRoute: () => rootRouteImport,
} as any)
const VendorOrdersRoute = VendorOrdersRouteImport.update({
  id: '/vendor/orders',
  path: '/vendor/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const VendorNotificationsRoute = VendorNotificationsRouteImport.update({
  id: '/vendor/notifications',
  path: '/vendor/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const VendorMessagesRoute = VendorMessagesRouteImport.update({
  id: '/vendor/messages',
  path: '/vendor/messages',
  getParentRoute: () => rootRouteImport,
} as any)
const VendorInventoryRoute = VendorInventoryRouteImport.update({
  id: '/vendor/inventory',
  path: '/vendor/inventory',
  getParentRoute: () => rootRouteImport,
} as any)
const VendorDashboardRoute = VendorDashboardRouteImport.update({
  id: '/vendor/dashboard',
  path: '/vendor/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DriverTripsRoute = DriverTripsRouteImport.update({
  id: '/driver/trips',
  path: '/driver/trips',
  getParentRoute: () => rootRouteImport,
} as any)
const DriverSupportRoute = DriverSupportRouteImport.update({
  id: '/driver/support',
  path: '/driver/support',
  getParentRoute: () => rootRouteImport,
} as any)
const DriverProfileRoute = DriverProfileRouteImport.update({
  id: '/driver/profile',
  path: '/driver/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const DriverNotificationsRoute = DriverNotificationsRouteImport.update({
  id: '/driver/notifications',
  path: '/driver/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const DriverIssuesRoute = DriverIssuesRouteImport.update({
  id: '/driver/issues',
  path: '/driver/issues',
  getParentRoute: () => rootRouteImport,
} as any)
const DriverHomeRoute = DriverHomeRouteImport.update({
  id: '/driver/home',
  path: '/driver/home',
  getParentRoute: () => rootRouteImport,
} as any)
const DriverEarningsRoute = DriverEarningsRouteImport.update({
  id: '/driver/earnings',
  path: '/driver/earnings',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomerVouchersRoute = CustomerVouchersRouteImport.update({
  id: '/customer/vouchers',
  path: '/customer/vouchers',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomerSupportRoute = CustomerSupportRouteImport.update({
  id: '/customer/support',
  path: '/customer/support',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomerSearchRoute = CustomerSearchRouteImport.update({
  id: '/customer/search',
  path: '/customer/search',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomerProfileRoute = CustomerProfileRouteImport.update({
  id: '/customer/profile',
  path: '/customer/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomerNotificationsRoute = CustomerNotificationsRouteImport.update({
  id: '/customer/notifications',
  path: '/customer/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomerHomeRoute = CustomerHomeRouteImport.update({
  id: '/customer/home',
  path: '/customer/home',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomerFavoritesRoute = CustomerFavoritesRouteImport.update({
  id: '/customer/favorites',
  path: '/customer/favorites',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomerCheckoutRoute = CustomerCheckoutRouteImport.update({
  id: '/customer/checkout',
  path: '/customer/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomerCartRoute = CustomerCartRouteImport.update({
  id: '/customer/cart',
  path: '/customer/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomerAddressesRoute = CustomerAddressesRouteImport.update({
  id: '/customer/addresses',
  path: '/customer/addresses',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminVouchersRoute = AdminVouchersRouteImport.update({
  id: '/admin/vouchers',
  path: '/admin/vouchers',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTicketsRoute = AdminTicketsRouteImport.update({
  id: '/admin/tickets',
  path: '/admin/tickets',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminStallsRoute = AdminStallsRouteImport.update({
  id: '/admin/stalls',
  path: '/admin/stalls',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/admin/settings',
  path: '/admin/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: '/admin/reports',
  path: '/admin/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminProductsRoute = AdminProductsRouteImport.update({
  id: '/admin/products',
  path: '/admin/products',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminOrdersRoute = AdminOrdersRouteImport.update({
  id: '/admin/orders',
  path: '/admin/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminNotificationsRoute = AdminNotificationsRouteImport.update({
  id: '/admin/notifications',
  path: '/admin/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminMarketsRoute = AdminMarketsRouteImport.update({
  id: '/admin/markets',
  path: '/admin/markets',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDriversRoute = AdminDriversRouteImport.update({
  id: '/admin/drivers',
  path: '/admin/drivers',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDispatchRoute = AdminDispatchRouteImport.update({
  id: '/admin/dispatch',
  path: '/admin/dispatch',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/admin/dashboard',
  path: '/admin/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomerOrdersIndexRoute = CustomerOrdersIndexRouteImport.update({
  id: '/customer/orders/',
  path: '/customer/orders/',
  getParentRoute: () => rootRouteImport,
} as any)
const VendorProductsNewRoute = VendorProductsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => VendorProductsRoute,
} as any)
const VendorOrdersIdRoute = VendorOrdersIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => VendorOrdersRoute,
} as any)
const DriverTripsIdRoute = DriverTripsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => DriverTripsRoute,
} as any)
const CustomerStallsIdRoute = CustomerStallsIdRouteImport.update({
  id: '/customer/stalls/$id',
  path: '/customer/stalls/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomerProfileEditRoute = CustomerProfileEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => CustomerProfileRoute,
} as any)
const CustomerProductsIdRoute = CustomerProductsIdRouteImport.update({
  id: '/customer/products/$id',
  path: '/customer/products/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomerMarketsIdRoute = CustomerMarketsIdRouteImport.update({
  id: '/customer/markets/$id',
  path: '/customer/markets/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomerCategorySlugRoute = CustomerCategorySlugRouteImport.update({
  id: '/customer/category/$slug',
  path: '/customer/category/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomerOrdersIdTrackingRoute =
  CustomerOrdersIdTrackingRouteImport.update({
    id: '/customer/orders/$id/tracking',
    path: '/customer/orders/$id/tracking',
    getParentRoute: () => rootRouteImport,
  } as any)
const CustomerOrdersIdRateRoute = CustomerOrdersIdRateRouteImport.update({
  id: '/customer/orders/$id/rate',
  path: '/customer/orders/$id/rate',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/dispatch': typeof AdminDispatchRoute
  '/admin/drivers': typeof AdminDriversRoute
  '/admin/markets': typeof AdminMarketsRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/stalls': typeof AdminStallsRoute
  '/admin/tickets': typeof AdminTicketsRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/vouchers': typeof AdminVouchersRoute
  '/customer/addresses': typeof CustomerAddressesRoute
  '/customer/cart': typeof CustomerCartRoute
  '/customer/checkout': typeof CustomerCheckoutRoute
  '/customer/favorites': typeof CustomerFavoritesRoute
  '/customer/home': typeof CustomerHomeRoute
  '/customer/notifications': typeof CustomerNotificationsRoute
  '/customer/profile': typeof CustomerProfileRouteWithChildren
  '/customer/search': typeof CustomerSearchRoute
  '/customer/support': typeof CustomerSupportRoute
  '/customer/vouchers': typeof CustomerVouchersRoute
  '/driver/earnings': typeof DriverEarningsRoute
  '/driver/home': typeof DriverHomeRoute
  '/driver/issues': typeof DriverIssuesRoute
  '/driver/notifications': typeof DriverNotificationsRoute
  '/driver/profile': typeof DriverProfileRoute
  '/driver/support': typeof DriverSupportRoute
  '/driver/trips': typeof DriverTripsRouteWithChildren
  '/vendor/dashboard': typeof VendorDashboardRoute
  '/vendor/inventory': typeof VendorInventoryRoute
  '/vendor/messages': typeof VendorMessagesRoute
  '/vendor/notifications': typeof VendorNotificationsRoute
  '/vendor/orders': typeof VendorOrdersRouteWithChildren
  '/vendor/products': typeof VendorProductsRouteWithChildren
  '/vendor/profile': typeof VendorProfileRoute
  '/vendor/revenue': typeof VendorRevenueRoute
  '/vendor/support': typeof VendorSupportRoute
  '/customer/category/$slug': typeof CustomerCategorySlugRoute
  '/customer/markets/$id': typeof CustomerMarketsIdRoute
  '/customer/products/$id': typeof CustomerProductsIdRoute
  '/customer/profile/edit': typeof CustomerProfileEditRoute
  '/customer/stalls/$id': typeof CustomerStallsIdRoute
  '/driver/trips/$id': typeof DriverTripsIdRoute
  '/vendor/orders/$id': typeof VendorOrdersIdRoute
  '/vendor/products/new': typeof VendorProductsNewRoute
  '/customer/orders/': typeof CustomerOrdersIndexRoute
  '/customer/orders/$id/rate': typeof CustomerOrdersIdRateRoute
  '/customer/orders/$id/tracking': typeof CustomerOrdersIdTrackingRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/dispatch': typeof AdminDispatchRoute
  '/admin/drivers': typeof AdminDriversRoute
  '/admin/markets': typeof AdminMarketsRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/stalls': typeof AdminStallsRoute
  '/admin/tickets': typeof AdminTicketsRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/vouchers': typeof AdminVouchersRoute
  '/customer/addresses': typeof CustomerAddressesRoute
  '/customer/cart': typeof CustomerCartRoute
  '/customer/checkout': typeof CustomerCheckoutRoute
  '/customer/favorites': typeof CustomerFavoritesRoute
  '/customer/home': typeof CustomerHomeRoute
  '/customer/notifications': typeof CustomerNotificationsRoute
  '/customer/profile': typeof CustomerProfileRouteWithChildren
  '/customer/search': typeof CustomerSearchRoute
  '/customer/support': typeof CustomerSupportRoute
  '/customer/vouchers': typeof CustomerVouchersRoute
  '/driver/earnings': typeof DriverEarningsRoute
  '/driver/home': typeof DriverHomeRoute
  '/driver/issues': typeof DriverIssuesRoute
  '/driver/notifications': typeof DriverNotificationsRoute
  '/driver/profile': typeof DriverProfileRoute
  '/driver/support': typeof DriverSupportRoute
  '/driver/trips': typeof DriverTripsRouteWithChildren
  '/vendor/dashboard': typeof VendorDashboardRoute
  '/vendor/inventory': typeof VendorInventoryRoute
  '/vendor/messages': typeof VendorMessagesRoute
  '/vendor/notifications': typeof VendorNotificationsRoute
  '/vendor/orders': typeof VendorOrdersRouteWithChildren
  '/vendor/products': typeof VendorProductsRouteWithChildren
  '/vendor/profile': typeof VendorProfileRoute
  '/vendor/revenue': typeof VendorRevenueRoute
  '/vendor/support': typeof VendorSupportRoute
  '/customer/category/$slug': typeof CustomerCategorySlugRoute
  '/customer/markets/$id': typeof CustomerMarketsIdRoute
  '/customer/products/$id': typeof CustomerProductsIdRoute
  '/customer/profile/edit': typeof CustomerProfileEditRoute
  '/customer/stalls/$id': typeof CustomerStallsIdRoute
  '/driver/trips/$id': typeof DriverTripsIdRoute
  '/vendor/orders/$id': typeof VendorOrdersIdRoute
  '/vendor/products/new': typeof VendorProductsNewRoute
  '/customer/orders': typeof CustomerOrdersIndexRoute
  '/customer/orders/$id/rate': typeof CustomerOrdersIdRateRoute
  '/customer/orders/$id/tracking': typeof CustomerOrdersIdTrackingRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/dispatch': typeof AdminDispatchRoute
  '/admin/drivers': typeof AdminDriversRoute
  '/admin/markets': typeof AdminMarketsRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/stalls': typeof AdminStallsRoute
  '/admin/tickets': typeof AdminTicketsRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/vouchers': typeof AdminVouchersRoute
  '/customer/addresses': typeof CustomerAddressesRoute
  '/customer/cart': typeof CustomerCartRoute
  '/customer/checkout': typeof CustomerCheckoutRoute
  '/customer/favorites': typeof CustomerFavoritesRoute
  '/customer/home': typeof CustomerHomeRoute
  '/customer/notifications': typeof CustomerNotificationsRoute
  '/customer/profile': typeof CustomerProfileRouteWithChildren
  '/customer/search': typeof CustomerSearchRoute
  '/customer/support': typeof CustomerSupportRoute
  '/customer/vouchers': typeof CustomerVouchersRoute
  '/driver/earnings': typeof DriverEarningsRoute
  '/driver/home': typeof DriverHomeRoute
  '/driver/issues': typeof DriverIssuesRoute
  '/driver/notifications': typeof DriverNotificationsRoute
  '/driver/profile': typeof DriverProfileRoute
  '/driver/support': typeof DriverSupportRoute
  '/driver/trips': typeof DriverTripsRouteWithChildren
  '/vendor/dashboard': typeof VendorDashboardRoute
  '/vendor/inventory': typeof VendorInventoryRoute
  '/vendor/messages': typeof VendorMessagesRoute
  '/vendor/notifications': typeof VendorNotificationsRoute
  '/vendor/orders': typeof VendorOrdersRouteWithChildren
  '/vendor/products': typeof VendorProductsRouteWithChildren
  '/vendor/profile': typeof VendorProfileRoute
  '/vendor/revenue': typeof VendorRevenueRoute
  '/vendor/support': typeof VendorSupportRoute
  '/customer/category/$slug': typeof CustomerCategorySlugRoute
  '/customer/markets/$id': typeof CustomerMarketsIdRoute
  '/customer/products/$id': typeof CustomerProductsIdRoute
  '/customer/profile/edit': typeof CustomerProfileEditRoute
  '/customer/stalls/$id': typeof CustomerStallsIdRoute
  '/driver/trips/$id': typeof DriverTripsIdRoute
  '/vendor/orders/$id': typeof VendorOrdersIdRoute
  '/vendor/products/new': typeof VendorProductsNewRoute
  '/customer/orders/': typeof CustomerOrdersIndexRoute
  '/customer/orders/$id/rate': typeof CustomerOrdersIdRateRoute
  '/customer/orders/$id/tracking': typeof CustomerOrdersIdTrackingRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin/dashboard'
    | '/admin/dispatch'
    | '/admin/drivers'
    | '/admin/markets'
    | '/admin/notifications'
    | '/admin/orders'
    | '/admin/products'
    | '/admin/reports'
    | '/admin/settings'
    | '/admin/stalls'
    | '/admin/tickets'
    | '/admin/users'
    | '/admin/vouchers'
    | '/customer/addresses'
    | '/customer/cart'
    | '/customer/checkout'
    | '/customer/favorites'
    | '/customer/home'
    | '/customer/notifications'
    | '/customer/profile'
    | '/customer/search'
    | '/customer/support'
    | '/customer/vouchers'
    | '/driver/earnings'
    | '/driver/home'
    | '/driver/issues'
    | '/driver/notifications'
    | '/driver/profile'
    | '/driver/support'
    | '/driver/trips'
    | '/vendor/dashboard'
    | '/vendor/inventory'
    | '/vendor/messages'
    | '/vendor/notifications'
    | '/vendor/orders'
    | '/vendor/products'
    | '/vendor/profile'
    | '/vendor/revenue'
    | '/vendor/support'
    | '/customer/category/$slug'
    | '/customer/markets/$id'
    | '/customer/products/$id'
    | '/customer/profile/edit'
    | '/customer/stalls/$id'
    | '/driver/trips/$id'
    | '/vendor/orders/$id'
    | '/vendor/products/new'
    | '/customer/orders/'
    | '/customer/orders/$id/rate'
    | '/customer/orders/$id/tracking'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin/dashboard'
    | '/admin/dispatch'
    | '/admin/drivers'
    | '/admin/markets'
    | '/admin/notifications'
    | '/admin/orders'
    | '/admin/products'
    | '/admin/reports'
    | '/admin/settings'
    | '/admin/stalls'
    | '/admin/tickets'
    | '/admin/users'
    | '/admin/vouchers'
    | '/customer/addresses'
    | '/customer/cart'
    | '/customer/checkout'
    | '/customer/favorites'
    | '/customer/home'
    | '/customer/notifications'
    | '/customer/profile'
    | '/customer/search'
    | '/customer/support'
    | '/customer/vouchers'
    | '/driver/earnings'
    | '/driver/home'
    | '/driver/issues'
    | '/driver/notifications'
    | '/driver/profile'
    | '/driver/support'
    | '/driver/trips'
    | '/vendor/dashboard'
    | '/vendor/inventory'
    | '/vendor/messages'
    | '/vendor/notifications'
    | '/vendor/orders'
    | '/vendor/products'
    | '/vendor/profile'
    | '/vendor/revenue'
    | '/vendor/support'
    | '/customer/category/$slug'
    | '/customer/markets/$id'
    | '/customer/products/$id'
    | '/customer/profile/edit'
    | '/customer/stalls/$id'
    | '/driver/trips/$id'
    | '/vendor/orders/$id'
    | '/vendor/products/new'
    | '/customer/orders'
    | '/customer/orders/$id/rate'
    | '/customer/orders/$id/tracking'
  id:
    | '__root__'
    | '/'
    | '/admin/dashboard'
    | '/admin/dispatch'
    | '/admin/drivers'
    | '/admin/markets'
    | '/admin/notifications'
    | '/admin/orders'
    | '/admin/products'
    | '/admin/reports'
    | '/admin/settings'
    | '/admin/stalls'
    | '/admin/tickets'
    | '/admin/users'
    | '/admin/vouchers'
    | '/customer/addresses'
    | '/customer/cart'
    | '/customer/checkout'
    | '/customer/favorites'
    | '/customer/home'
    | '/customer/notifications'
    | '/customer/profile'
    | '/customer/search'
    | '/customer/support'
    | '/customer/vouchers'
    | '/driver/earnings'
    | '/driver/home'
    | '/driver/issues'
    | '/driver/notifications'
    | '/driver/profile'
    | '/driver/support'
    | '/driver/trips'
    | '/vendor/dashboard'
    | '/vendor/inventory'
    | '/vendor/messages'
    | '/vendor/notifications'
    | '/vendor/orders'
    | '/vendor/products'
    | '/vendor/profile'
    | '/vendor/revenue'
    | '/vendor/support'
    | '/customer/category/$slug'
    | '/customer/markets/$id'
    | '/customer/products/$id'
    | '/customer/profile/edit'
    | '/customer/stalls/$id'
    | '/driver/trips/$id'
    | '/vendor/orders/$id'
    | '/vendor/products/new'
    | '/customer/orders/'
    | '/customer/orders/$id/rate'
    | '/customer/orders/$id/tracking'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminDispatchRoute: typeof AdminDispatchRoute
  AdminDriversRoute: typeof AdminDriversRoute
  AdminMarketsRoute: typeof AdminMarketsRoute
  AdminNotificationsRoute: typeof AdminNotificationsRoute
  AdminOrdersRoute: typeof AdminOrdersRoute
  AdminProductsRoute: typeof AdminProductsRoute
  AdminReportsRoute: typeof AdminReportsRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminStallsRoute: typeof AdminStallsRoute
  AdminTicketsRoute: typeof AdminTicketsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminVouchersRoute: typeof AdminVouchersRoute
  CustomerAddressesRoute: typeof CustomerAddressesRoute
  CustomerCartRoute: typeof CustomerCartRoute
  CustomerCheckoutRoute: typeof CustomerCheckoutRoute
  CustomerFavoritesRoute: typeof CustomerFavoritesRoute
  CustomerHomeRoute: typeof CustomerHomeRoute
  CustomerNotificationsRoute: typeof CustomerNotificationsRoute
  CustomerProfileRoute: typeof CustomerProfileRouteWithChildren
  CustomerSearchRoute: typeof CustomerSearchRoute
  CustomerSupportRoute: typeof CustomerSupportRoute
  CustomerVouchersRoute: typeof CustomerVouchersRoute
  DriverEarningsRoute: typeof DriverEarningsRoute
  DriverHomeRoute: typeof DriverHomeRoute
  DriverIssuesRoute: typeof DriverIssuesRoute
  DriverNotificationsRoute: typeof DriverNotificationsRoute
  DriverProfileRoute: typeof DriverProfileRoute
  DriverSupportRoute: typeof DriverSupportRoute
  DriverTripsRoute: typeof DriverTripsRouteWithChildren
  VendorDashboardRoute: typeof VendorDashboardRoute
  VendorInventoryRoute: typeof VendorInventoryRoute
  VendorMessagesRoute: typeof VendorMessagesRoute
  VendorNotificationsRoute: typeof VendorNotificationsRoute
  VendorOrdersRoute: typeof VendorOrdersRouteWithChildren
  VendorProductsRoute: typeof VendorProductsRouteWithChildren
  VendorProfileRoute: typeof VendorProfileRoute
  VendorRevenueRoute: typeof VendorRevenueRoute
  VendorSupportRoute: typeof VendorSupportRoute
  CustomerCategorySlugRoute: typeof CustomerCategorySlugRoute
  CustomerMarketsIdRoute: typeof CustomerMarketsIdRoute
  CustomerProductsIdRoute: typeof CustomerProductsIdRoute
  CustomerStallsIdRoute: typeof CustomerStallsIdRoute
  CustomerOrdersIndexRoute: typeof CustomerOrdersIndexRoute
  CustomerOrdersIdRateRoute: typeof CustomerOrdersIdRateRoute
  CustomerOrdersIdTrackingRoute: typeof CustomerOrdersIdTrackingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vendor/support': {
      id: '/vendor/support'
      path: '/vendor/support'
      fullPath: '/vendor/support'
      preLoaderRoute: typeof VendorSupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vendor/revenue': {
      id: '/vendor/revenue'
      path: '/vendor/revenue'
      fullPath: '/vendor/revenue'
      preLoaderRoute: typeof VendorRevenueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vendor/profile': {
      id: '/vendor/profile'
      path: '/vendor/profile'
      fullPath: '/vendor/profile'
      preLoaderRoute: typeof VendorProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vendor/products': {
      id: '/vendor/products'
      path: '/vendor/products'
      fullPath: '/vendor/products'
      preLoaderRoute: typeof VendorProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vendor/orders': {
      id: '/vendor/orders'
      path: '/vendor/orders'
      fullPath: '/vendor/orders'
      preLoaderRoute: typeof VendorOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vendor/notifications': {
      id: '/vendor/notifications'
      path: '/vendor/notifications'
      fullPath: '/vendor/notifications'
      preLoaderRoute: typeof VendorNotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vendor/messages': {
      id: '/vendor/messages'
      path: '/vendor/messages'
      fullPath: '/vendor/messages'
      preLoaderRoute: typeof VendorMessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vendor/inventory': {
      id: '/vendor/inventory'
      path: '/vendor/inventory'
      fullPath: '/vendor/inventory'
      preLoaderRoute: typeof VendorInventoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vendor/dashboard': {
      id: '/vendor/dashboard'
      path: '/vendor/dashboard'
      fullPath: '/vendor/dashboard'
      preLoaderRoute: typeof VendorDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/driver/trips': {
      id: '/driver/trips'
      path: '/driver/trips'
      fullPath: '/driver/trips'
      preLoaderRoute: typeof DriverTripsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/driver/support': {
      id: '/driver/support'
      path: '/driver/support'
      fullPath: '/driver/support'
      preLoaderRoute: typeof DriverSupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/driver/profile': {
      id: '/driver/profile'
      path: '/driver/profile'
      fullPath: '/driver/profile'
      preLoaderRoute: typeof DriverProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/driver/notifications': {
      id: '/driver/notifications'
      path: '/driver/notifications'
      fullPath: '/driver/notifications'
      preLoaderRoute: typeof DriverNotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/driver/issues': {
      id: '/driver/issues'
      path: '/driver/issues'
      fullPath: '/driver/issues'
      preLoaderRoute: typeof DriverIssuesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/driver/home': {
      id: '/driver/home'
      path: '/driver/home'
      fullPath: '/driver/home'
      preLoaderRoute: typeof DriverHomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/driver/earnings': {
      id: '/driver/earnings'
      path: '/driver/earnings'
      fullPath: '/driver/earnings'
      preLoaderRoute: typeof DriverEarningsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customer/vouchers': {
      id: '/customer/vouchers'
      path: '/customer/vouchers'
      fullPath: '/customer/vouchers'
      preLoaderRoute: typeof CustomerVouchersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customer/support': {
      id: '/customer/support'
      path: '/customer/support'
      fullPath: '/customer/support'
      preLoaderRoute: typeof CustomerSupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customer/search': {
      id: '/customer/search'
      path: '/customer/search'
      fullPath: '/customer/search'
      preLoaderRoute: typeof CustomerSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customer/profile': {
      id: '/customer/profile'
      path: '/customer/profile'
      fullPath: '/customer/profile'
      preLoaderRoute: typeof CustomerProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customer/notifications': {
      id: '/customer/notifications'
      path: '/customer/notifications'
      fullPath: '/customer/notifications'
      preLoaderRoute: typeof CustomerNotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customer/home': {
      id: '/customer/home'
      path: '/customer/home'
      fullPath: '/customer/home'
      preLoaderRoute: typeof CustomerHomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customer/favorites': {
      id: '/customer/favorites'
      path: '/customer/favorites'
      fullPath: '/customer/favorites'
      preLoaderRoute: typeof CustomerFavoritesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customer/checkout': {
      id: '/customer/checkout'
      path: '/customer/checkout'
      fullPath: '/customer/checkout'
      preLoaderRoute: typeof CustomerCheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customer/cart': {
      id: '/customer/cart'
      path: '/customer/cart'
      fullPath: '/customer/cart'
      preLoaderRoute: typeof CustomerCartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customer/addresses': {
      id: '/customer/addresses'
      path: '/customer/addresses'
      fullPath: '/customer/addresses'
      preLoaderRoute: typeof CustomerAddressesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/vouchers': {
      id: '/admin/vouchers'
      path: '/admin/vouchers'
      fullPath: '/admin/vouchers'
      preLoaderRoute: typeof AdminVouchersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/tickets': {
      id: '/admin/tickets'
      path: '/admin/tickets'
      fullPath: '/admin/tickets'
      preLoaderRoute: typeof AdminTicketsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/stalls': {
      id: '/admin/stalls'
      path: '/admin/stalls'
      fullPath: '/admin/stalls'
      preLoaderRoute: typeof AdminStallsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/admin/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/reports': {
      id: '/admin/reports'
      path: '/admin/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/products': {
      id: '/admin/products'
      path: '/admin/products'
      fullPath: '/admin/products'
      preLoaderRoute: typeof AdminProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/orders': {
      id: '/admin/orders'
      path: '/admin/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof AdminOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/notifications': {
      id: '/admin/notifications'
      path: '/admin/notifications'
      fullPath: '/admin/notifications'
      preLoaderRoute: typeof AdminNotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/markets': {
      id: '/admin/markets'
      path: '/admin/markets'
      fullPath: '/admin/markets'
      preLoaderRoute: typeof AdminMarketsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/drivers': {
      id: '/admin/drivers'
      path: '/admin/drivers'
      fullPath: '/admin/drivers'
      preLoaderRoute: typeof AdminDriversRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/dispatch': {
      id: '/admin/dispatch'
      path: '/admin/dispatch'
      fullPath: '/admin/dispatch'
      preLoaderRoute: typeof AdminDispatchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/admin/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customer/orders/': {
      id: '/customer/orders/'
      path: '/customer/orders'
      fullPath: '/customer/orders/'
      preLoaderRoute: typeof CustomerOrdersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vendor/products/new': {
      id: '/vendor/products/new'
      path: '/new'
      fullPath: '/vendor/products/new'
      preLoaderRoute: typeof VendorProductsNewRouteImport
      parentRoute: typeof VendorProductsRoute
    }
    '/vendor/orders/$id': {
      id: '/vendor/orders/$id'
      path: '/$id'
      fullPath: '/vendor/orders/$id'
      preLoaderRoute: typeof VendorOrdersIdRouteImport
      parentRoute: typeof VendorOrdersRoute
    }
    '/driver/trips/$id': {
      id: '/driver/trips/$id'
      path: '/$id'
      fullPath: '/driver/trips/$id'
      preLoaderRoute: typeof DriverTripsIdRouteImport
      parentRoute: typeof DriverTripsRoute
    }
    '/customer/stalls/$id': {
      id: '/customer/stalls/$id'
      path: '/customer/stalls/$id'
      fullPath: '/customer/stalls/$id'
      preLoaderRoute: typeof CustomerStallsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customer/profile/edit': {
      id: '/customer/profile/edit'
      path: '/edit'
      fullPath: '/customer/profile/edit'
      preLoaderRoute: typeof CustomerProfileEditRouteImport
      parentRoute: typeof CustomerProfileRoute
    }
    '/customer/products/$id': {
      id: '/customer/products/$id'
      path: '/customer/products/$id'
      fullPath: '/customer/products/$id'
      preLoaderRoute: typeof CustomerProductsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customer/markets/$id': {
      id: '/customer/markets/$id'
      path: '/customer/markets/$id'
      fullPath: '/customer/markets/$id'
      preLoaderRoute: typeof CustomerMarketsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customer/category/$slug': {
      id: '/customer/category/$slug'
      path: '/customer/category/$slug'
      fullPath: '/customer/category/$slug'
      preLoaderRoute: typeof CustomerCategorySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customer/orders/$id/tracking': {
      id: '/customer/orders/$id/tracking'
      path: '/customer/orders/$id/tracking'
      fullPath: '/customer/orders/$id/tracking'
      preLoaderRoute: typeof CustomerOrdersIdTrackingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customer/orders/$id/rate': {
      id: '/customer/orders/$id/rate'
      path: '/customer/orders/$id/rate'
      fullPath: '/customer/orders/$id/rate'
      preLoaderRoute: typeof CustomerOrdersIdRateRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface CustomerProfileRouteChildren {
  CustomerProfileEditRoute: typeof CustomerProfileEditRoute
}

const CustomerProfileRouteChildren: CustomerProfileRouteChildren = {
  CustomerProfileEditRoute: CustomerProfileEditRoute,
}

const CustomerProfileRouteWithChildren = CustomerProfileRoute._addFileChildren(
  CustomerProfileRouteChildren,
)

interface DriverTripsRouteChildren {
  DriverTripsIdRoute: typeof DriverTripsIdRoute
}

const DriverTripsRouteChildren: DriverTripsRouteChildren = {
  DriverTripsIdRoute: DriverTripsIdRoute,
}

const DriverTripsRouteWithChildren = DriverTripsRoute._addFileChildren(
  DriverTripsRouteChildren,
)

interface VendorOrdersRouteChildren {
  VendorOrdersIdRoute: typeof VendorOrdersIdRoute
}

const VendorOrdersRouteChildren: VendorOrdersRouteChildren = {
  VendorOrdersIdRoute: VendorOrdersIdRoute,
}

const VendorOrdersRouteWithChildren = VendorOrdersRoute._addFileChildren(
  VendorOrdersRouteChildren,
)

interface VendorProductsRouteChildren {
  VendorProductsNewRoute: typeof VendorProductsNewRoute
}

const VendorProductsRouteChildren: VendorProductsRouteChildren = {
  VendorProductsNewRoute: VendorProductsNewRoute,
}

const VendorProductsRouteWithChildren = VendorProductsRoute._addFileChildren(
  VendorProductsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminDispatchRoute: AdminDispatchRoute,
  AdminDriversRoute: AdminDriversRoute,
  AdminMarketsRoute: AdminMarketsRoute,
  AdminNotificationsRoute: AdminNotificationsRoute,
  AdminOrdersRoute: AdminOrdersRoute,
  AdminProductsRoute: AdminProductsRoute,
  AdminReportsRoute: AdminReportsRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminStallsRoute: AdminStallsRoute,
  AdminTicketsRoute: AdminTicketsRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminVouchersRoute: AdminVouchersRoute,
  CustomerAddressesRoute: CustomerAddressesRoute,
  CustomerCartRoute: CustomerCartRoute,
  CustomerCheckoutRoute: CustomerCheckoutRoute,
  CustomerFavoritesRoute: CustomerFavoritesRoute,
  CustomerHomeRoute: CustomerHomeRoute,
  CustomerNotificationsRoute: CustomerNotificationsRoute,
  CustomerProfileRoute: CustomerProfileRouteWithChildren,
  CustomerSearchRoute: CustomerSearchRoute,
  CustomerSupportRoute: CustomerSupportRoute,
  CustomerVouchersRoute: CustomerVouchersRoute,
  DriverEarningsRoute: DriverEarningsRoute,
  DriverHomeRoute: DriverHomeRoute,
  DriverIssuesRoute: DriverIssuesRoute,
  DriverNotificationsRoute: DriverNotificationsRoute,
  DriverProfileRoute: DriverProfileRoute,
  DriverSupportRoute: DriverSupportRoute,
  DriverTripsRoute: DriverTripsRouteWithChildren,
  VendorDashboardRoute: VendorDashboardRoute,
  VendorInventoryRoute: VendorInventoryRoute,
  VendorMessagesRoute: VendorMessagesRoute,
  VendorNotificationsRoute: VendorNotificationsRoute,
  VendorOrdersRoute: VendorOrdersRouteWithChildren,
  VendorProductsRoute: VendorProductsRouteWithChildren,
  VendorProfileRoute: VendorProfileRoute,
  VendorRevenueRoute: VendorRevenueRoute,
  VendorSupportRoute: VendorSupportRoute,
  CustomerCategorySlugRoute: CustomerCategorySlugRoute,
  CustomerMarketsIdRoute: CustomerMarketsIdRoute,
  CustomerProductsIdRoute: CustomerProductsIdRoute,
  CustomerStallsIdRoute: CustomerStallsIdRoute,
  CustomerOrdersIndexRoute: CustomerOrdersIndexRoute,
  CustomerOrdersIdRateRoute: CustomerOrdersIdRateRoute,
  CustomerOrdersIdTrackingRoute: CustomerOrdersIdTrackingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
